### ISSUE TITLE
mobile device button disabled

### ISSUE THREAD

**Issue by douglance** [springbok/MLM2PRO-GSPro-Connector#128]
When I boot up the latest release, the mobile device button is greyed out and disabled. I do not see any additional setup instructions in any of the resources linked or that I could find on YouTube or elsewhere. Please advise. Thanks!

**Comment by wonder99** [comment]
This does look like a bug.  To work around it, click the gear icon (settings), and click the Launch Monitor dropdown and change the setting to anything else.  Click save, OK, Close, and the mobile device button should be reenabled.  It shouldn't happen again, I think it's because there were no previous settings

**Comment by wonder99** [comment]
@springbok It seems that the default device is a Bluetooth one, and when a bluetooth device is selected, the Mobile device button gets disabled.

**Comment by springbok** [comment]
I made the Rapsodo BT device the default as I though most people would be using this LM, if a BT LM is selected then there is no no need to define a device so its disabled. You can easily overcome this by selecting the correct LM from Settings, if its an OCR based LM then the device button will be enabled.
