### ISSUE TITLE
Pull in Garmin R10 Data?

### ISSUE THREAD

**Issue by Gilliganmp** [springbok/MLM2PRO-GSPro-Connector#76]
I’m searching for a solution to use Exputt along with the Garmin R10 and so far, your connector is the only option to integrate Exputt to GSPro. Is it possible to add an additional launch monitor option that pulls in the Garmin R10 data utilizing the existing gsp-r10-adapter from mholow? Or going the other route, is there a way to send the putting data to gsp-r10-adapter similar to how cam-putting-py is able to launch and send data?

**Comment by springbok** [comment]
There two ways to go about this we can train the OCR to recognise the R10 app which you would then mirror the same we do for the Rapsodo app. Or we can the R10 connector connect to the mlm2 connector and the mlm2 connector to gspro allowing you to use exputt. The easiest would be training the OCR font but you lose direct connectivity to the R10. I have started work on option 2 but it will take some time to develop.

**Comment by Gilliganmp** [comment]
Amazing! I wasn’t even sure if this would be possible but it definitely would be interesting to have the MLM2 Connector to be the ultimate all-in-one connector tool

**Comment by springbok** [comment]
I don't own an R10 so I will be depending on R10 owners to help with testing.

**Comment by Gilliganmp** [comment]
You can count on me for any testing you need

**Comment by springbok** [comment]
Thanks will do.

**Comment by GhostRider076** [comment]
I would be interested in helping out with testing.  Would love to see the R10 with the direct Bluetooth connection supported.  I also have webcam putting that I am setting up as well.

**Comment by springbok** [comment]
Some good news here is the first version that will interface with the R10 connector. Please note I’ve done VERY limited testing so expect issues.

https://1drv.ms/u/s!Agx7aYfjrZJ8qTq7_iurLMWyixZ5?e=X71Zh3

When you start the MLM connector you need to go to ‘Settings’, change the Launch Monitor to ‘R10’ and take note of the IP address and port for the R10, change these to suit. You will then need to update the config settings of your R10 connector to point to this IP address and port instead of the GSPro IP address and port.

Once done, start the R10 server on the MLM connector, start GSPro and connect to it from the MLM connector, then start the R10 connector hopefully it will connect to the R10 server running in the MLM connector.

To use ExPutt, you will need a HDMI-USB video capture card, plug the HDMI cable from the ExPutt into the card, go into ‘Putting Settings’, change to ExPutt, do your ROI’s for ExPutt. There are videos on how to do all of this on the github site.

**Comment by Gilliganmp** [comment]
I’ll start testing it out today!On Mar 12, 2024, at 2:10 AM, Etienne van Tonder ***@***.***> wrote:﻿
Some good news here is the first version that will interface with the R10 connector. Please note I’ve done VERY limited testing so expect issues.
https://1drv.ms/u/s!Agx7aYfjrZJ8qTq7_iurLMWyixZ5?e=X71Zh3
When you start the MLM connector you need to go to ‘Settings’, change the Launch Monitor to ‘R10’ and take note of the IP address and port for the R10, change these to suit. You will then need to update the config settings of your R10 connector to point to this IP address and port instead of the GSPro IP address and port.
Once done, start the R10 server on the MLM connector, start GSPro and connect to it from the MLM connector, then start the R10 connector hopefully it will connect to the R10 server running in the MLM connector.
To use ExPutt, you will need a HDMI-USB video capture card, plug the HDMI cable from the ExPutt into the card, go into ‘Putting Settings’, change to ExPutt, do your ROI’s for ExPutt. There are videos on how to do all of this on the github site.

**Comment by Gilliganmp** [comment]
It appears there is an error that is not allowing the application to launch. The previous version still launches fine but this version just spins

**Comment by GhostRider076** [comment]
Just tried on my end and it is the same.  Thanks for working on this!

**Comment by springbok** [comment]
Ok not a great start :) 

I’ve been doing testing from the IDE and hadn’t tested using the exe so maybe an issue with exe, I’ll have a look.

**Comment by Gilliganmp** [comment]
Hahaha!The fact that you are even trying to make it work is amazing! Just gotta be ready for Masters weekend ;)On Mar 12, 2024, at 2:07 PM, Etienne van Tonder ***@***.***> wrote:﻿
Ok not a great start :) 



I’ve been doing testing from the IDE and hadn’t tested using the exe so maybe an issue with exe, I’ll have a look.

**Comment by springbok** [comment]
The problem is with the mlm2pro setup, I originally tested it but must have changed something causing the issue if you have the mlm selected as the LM.  I then only tested the R10 changes and never retested the mlm. One way around the issue is manually updating appdata\settings.json and change: `"device_id": "R10",` hopefully that should get it running. I'll have a look into the problem and post an updated link once its resolved.

**Comment by springbok** [comment]
I'm away at the moment so I'm unable to fully test this release, it does now start up correctly. If there are more issues it may have to wait till I get back.

https://1drv.ms/u/s!Agx7aYfjrZJ8qTtPFGWLCuGsF0OW?e=rlwCWT

**Comment by GhostRider076** [comment]
Thanks.  It starts fine now, should be able to give it a try over the next few days.

**Comment by springbok** [comment]
I've added a Garmin R10 Bluetooth connection to the connector if anyone want to give it a test run.

https://1drv.ms/u/c/7c92ade387697b0c/ERzsMDn8kDJApVB2aiGYjiUBLSlJpjMy8HI__N924wGsCw?e=AmdRMm

**Comment by springbok** [comment]
The new version of the app containing r10 Bluetooth support has been released.
